version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - mysql
    env_file: .env

  mysql:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"
